import = [
  "/home/obathily/.nvm/versions/node/v20.15.1/lib/node_modules/alacritty-themes/themes/github_light.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 10

  [font.bold]
  family = "RobotoMono Nerd Font"
  style = "Bold"

  [font.bold_italic]
  family = "RobotoMono Nerd Font"
  style = "Bold Italic"

  [font.italic]
  family = "RobotoMono Nerd Font"
  style = "Italic"

  [font.normal]
  family = "RobotoMono Nerd Font"
  style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[window]
dynamic_padding = true
startup_mode = "Fullscreen"
